
export const LEADERBOARD_CONTRACT =
  "CDFH24FTC35NUKSOCFPXUYTTA2RHXCCDNCV7WL4CYAKTXECUAQ4AJUKK";

export const TASK_CONTRACT =
  "CA5RPNPLWGDNPCTFGGULF2SS7Y4PEGQT5ULJ5XJTE52423PLBFBTODE3";

export const TOKEN_CONTRACT =
  "CCQF6TLXQIU7VMH7YUOWLMYKDOLUBUGAGIR57MU66TXHYCI7HP5DEWIK";

export const ACHIEVEMENT_NFT_CONTRACT =
  "CB5TYSXAYECB3AI7JSXWKN5OAEUJ4OFICQ2ZF56DKDZOBX35Y25H7ENT";

export const RPC_URL = "https://soroban-testnet.stellar.org";